CFB2019 <- read.csv("~/OneDrive - SectorShield Inc/2020 Summer/CFB2019-v2.csv")
View(CFB2019) 
attach(CFB2019)
View(RankData)
probitmodel1<-glm(WR ~.,family=binomial(link='probit'),data=RankData)
summary(probitmodel1)
drop1(probitmodel1,test = "LRT")
warnings()
probitmodel2<-update(probitmodel1, .~. -Rushing.Off.Rank)
summary(probitmodel2)
drop1(probitmodel2,test = "LRT")
probitmodel3<-update(probitmodel2, .~. -Punt.Return.Def.Rank)
summary(probitmodel3)
drop1(probitmodel3,test = "LRT")
probitmodel4<-update(probitmodel3, .~. -Scoring.Off.Rank)
summary(probitmodel4)
drop1(probitmodel4,test = "LRT")
probitmodel5<-update(probitmodel4, .~. -X3rd.Down.Rank)
summary(probitmodel5)
drop1(probitmodel5,test = "LRT")
probitmodel6<-update(probitmodel5, .~. -Redzone.Off.Rank)
summary(probitmodel6)
drop1(probitmodel6,test = "LRT")
probitmodel7<-update(probitmodel6, .~. -Pass.Def.Rank)
summary(probitmodel7)
drop1(probitmodel7,test = "LRT")
probitmodel8<-update(probitmodel7, .~. -Rushing.Def.Rank)
summary(probitmodel8)
drop1(probitmodel8,test = "LRT")
probitmodel9<-update(probitmodel8, .~. -Tackle.for.Loss.Rank)
summary(probitmodel9)
drop1(probitmodel9,test = "LRT")
probitmodel10<-update(probitmodel9, .~. -Turnover.Rank)
summary(probitmodel10)
drop1(probitmodel10,test = "LRT")
probitmodel11<-update(probitmodel10, .~. -Scoring.Def.Rank)
summary(probitmodel11)
drop1(probitmodel11,test = "LRT")
probitmodel12<-update(probitmodel11, .~. -Kickoff.Return.Rank)
summary(probitmodel12)
drop1(probitmodel12,test = "LRT")
probitmodel13<-update(probitmodel12, .~. -X4th.Down.Rank)
summary(probitmodel13)
drop1(probitmodel13,test = "LRT")
probitmodel14<-update(probitmodel13, .~. -X4rd.Down.Def.Rank)
summary(probitmodel14)
drop1(probitmodel14,test = "LRT")
probitmodel15<-update(probitmodel14, .~. -Redzone.Def.Rank)
summary(probitmodel15)
drop1(probitmodel15,test = "LRT")
probitmodel16<-update(probitmodel15, .~. -Penalty.Rank)
summary(probitmodel16)
drop1(probitmodel16,test = "LRT")
probitmodel17<-update(probitmodel16, .~. -Punt.Return.Rank)
summary(probitmodel17)
drop1(probitmodel17,test = "LRT")
library(ROCR)

