CFB2019 <- read.csv("~/OneDrive - SectorShield Inc/2020 Summer/CFB2019-v2.csv")
View(CFB2019) 
attach(CFB2019)
RankVars <- c("Def.Rank", "First.Down.Def.Rank", "Kickoff.Return.Def.Rank","Kickoff.Return.Rank","Off.Rank","Pass.Def.Rank","Penalty.Rank","Punt.Return.Def.Rank","Punt.Return.Rank","Redzone.Def.Rank","Redzone.Off.Rank","Rushing.Def.Rank","Rushing.Off.Rank","Sack.Rank","Scoring.Def.Rank","Scoring.Off.Rank","Tackle.for.Loss.Rank","Time.of.Possession.Rank","Turnover.Rank","X4rd.Down.Def.Rank","X3rd.Down.Rank","X4th.Down.Rank")
RankData <- CFB2019[RankVars]
model1 <- glm(as.factor(WR) ~.,family=binomial(link='logit'),data=RankData) ##question 2--logit
summary(model1)
model2 <- glm(Ten~.,family=binomial(link='logit'),data=RankData)
summary(model2)
model3 <- glm(Bowl~.,family=binomial(link='logit'),data=RankData)
summary(model3)
drop1(model1,test = "LRT")
model1.v2<-update(model1, .~. -Rushing.Off.Rank)
summary(model1.v2)
drop1(model1.v2,test = "LRT")
model1.v3<-update(model1.v2, .~. -Scoring.Off.Rank)
summary(model1.v3)
drop1(model1.v3,test = "LRT")
model1.v4<-update(model1.v3, .~. -Punt.Return.Def.Rank)
summary(model1.v4)
drop1(model1.v4,test = "LRT")
model1.v5<-update(model1.v4, .~. -X3rd.Down.Rank)
summary(model1.v5)
drop1(model1.v5,test = "LRT")
model1.v6<-update(model1.v5, .~. -Redzone.Off.Rank)
summary(model1.v6)
drop1(model1.v6,test = "LRT")
model1.v7<-update(model1.v6, .~. -Pass.Def.Rank)
summary(model1.v7)
drop1(model1.v7,test = "LRT")
model1.v8<-update(model1.v7, .~. -Rushing.Def.Rank)
summary(model1.v8)
drop1(model1.v8,test = "LRT")
model1.v9<-update(model1.v8, .~. -Tackle.for.Loss.Rank)
summary(model1.v9)
drop1(model1.v9,test = "LRT")
model1.v10<-update(model1.v9, .~. -Turnover.Rank)
summary(model1.v10)
drop1(model1.v10,test = "LRT")
model1.v11<-update(model1.v10, .~. -Scoring.Def.Rank)
summary(model1.v11)
drop1(model1.v11,test = "LRT")
model1.v12<-update(model1.v11, .~. -Kickoff.Return.Rank)
summary(model1.v12)
drop1(model1.v12,test = "LRT")
model1.v13<-update(model1.v12, .~. -X4th.Down.Rank)
summary(model1.v13)
drop1(model1.v13,test = "LRT")
model1.v14<-update(model1.v13, .~. -X4rd.Down.Def.Rank)
summary(model1.v14)
drop1(model1.v14,test = "LRT")
model1.v15<-update(model1.v14, .~. -Redzone.Def.Rank)
summary(model1.v15)
drop1(model1.v15,test = "LRT")
model1.v16<-update(model1.v15, .~. -Penalty.Rank)
summary(model1.v16)
drop1(model1.v16,test = "LRT")
model1.v17<-update(model1.v16, .~. -Punt.Return.Rank)
summary(model1.v17)
drop1(model1.v17,test = "LRT")
model1.v18<-update(model1.v17, .~. -Sack.Rank)
summary(model1.v18)
drop1(model1.v18,test = "LRT")
